version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stickerize
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Uncomment this section when you have the inference service ready
  # inference:
  #   build:
  #     context: ./inference
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7860:7860"
  #   volumes:
  #     - ./inference:/app
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

volumes:
  postgres_data:
  redis_data:
