# Aiken project configuration for Discord Bot Payment System
name = "stickerize-bot/discord-payment-contracts"
version = "1.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Smart contracts for Discord bot ADA payment processing"

[repository]
user = "stickerize-bot"
project = "payment-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
